-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 08:18:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema toolmasters
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema toolmasters
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `toolmasters` DEFAULT CHARACTER SET utf8 ;
USE `toolmasters` ;

-- -----------------------------------------------------
-- Table `toolmasters`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolmasters`.`usuarios` (
  `idusuarios` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idusuarios`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`idusuarios` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `toolmasters`.`cadastro_ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `toolmasters`.`cadastro_ferramenta` (
  `idcadastro_ferramenta` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `numero_serie` INT NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `nome_ferramenta` VARCHAR(100) NOT NULL,
  `imagem` VARCHAR(200) NOT NULL,
  `usuarios_idusuarios` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcadastro_ferramenta`),
  UNIQUE INDEX `idcadastro_ferramenta_UNIQUE` (`idcadastro_ferramenta` ASC),
  INDEX `fk_cadastro_ferramenta_usuarios_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_cadastro_ferramenta_usuarios`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `toolmasters`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
